let shopItemsData = [
    {
        id: "vuhhfsgfssf",
        name: "Camisa Social Azul",
        price: 45,
        desc: "Ser chic é se sustentavel",
        img: "img/roupas/fem1.jpg",
    },
    {
        id: "mnkjhbhf",
        name: "Camisa Social Preta",
        price: 100,
        desc: "Nossa roupa tras uma paz",
        img: "img/roupas/fem2.png",
    },
    {
        id: "nbvhvgcdfx",
        name: "Camisa Social Branca",
        price: 25,
        desc: "Seja sustentavel, seja chic!",
        img: "img/roupas/fem3.png",
    },
    {
        id: "gfdsrxkjnhb",
        name: "Camisa Social Rosa",
        price: 200,
        desc: "Seja sustentavel ",
        img: "img/roupas/fem4.jpg",
    },
    {
        id: "abc",
        name: "Calça Verde Clara",
        price: 249,
        desc: "Seja Northfield",
        img: "img/roupas/fem6.jpg",
    },
    {
        id: "def",
        name: "Calça Verde Escuro",
        price: 70,
        desc: "Seja perfeita",
        img: "img/roupas/fem7.jpg",
    },
    {
        id: "ghi",
        name: "Calça Rosa",
        price: 80,
        desc: "Seja linda ",
        img: "img/roupas/fem10.jpg",
    },
    {
        id: "ggfhgjhg",
        name:"Calça Preta",
        price: 50,
        desc: "Seja incrível",
        img: "img/roupas/fem11.jpg",
    },
    
    {
        id: "lnkjhjjhbb",
        name: "Calça Escura",
        price: 45,
        desc: "Seja a melhor ",
        img: "img/roupas/fem12.jpg",
    },
    {
        id: "kjhbkjbh",
        name: "Calça Violeta",
        price: 100,
        desc: "Seja você mesma ",
        img: "img/roupas/fem.13.jpg",
    },
    {
        id: "kjhbkj",
        name: "Vestido Rodado",
        price: 200,
        desc: "Você é Northfield",
        img: "img/roupas/fem14.jpg",
    },
    {
        id: "kjhuifgytd",
        name: "Vestido Longo",
        price: 150,
        desc: "Você é a melhor",
        img: "img/roupas/fem15.jpg",
    },
    {
        id: "Um",
        name: "Camiseta Amazônia",
        price: 45,
        desc: "Edição Amazônia Marinha",
        img: "img/roupas/masc1.jpg",
    },
    {
        id: "Dois",
        name: "Camiseta Linho",
        price: 100,
        desc: "Leve 100% Linho",
        img: "img/roupas/masc2.jpg",
    },
    {
        id: "Três",
        name: "Camiseta Preta",
        price: 120,
        desc: "100% Algodão",
        img: "img/roupas/masc3.jpg",
    },
    {
        id: "Quatro",
        name: "Camisa Xadrez Azul",
        price: 152,
        desc: "Tecido 100% Algodão",
        img: "img/roupas/masc4.jpg",
    },
    {
        id: "Cinco",
        name: "Camisa de Linho",
        price: 69,
        desc: "Camisa Branca Linho ",
        img: "img/roupas/masc5.jpg",
    },
    {
        id: "Seis",
        name: "Camisa Longa",
        price: 200,
        desc: "Ótima para dormir",
        img: "img/roupas/masc6.jpg",
    },
    {
        id: "Sete",
        name: "Conjunto Camisa e Casaco Masc.",
        price: 498,
        desc: "Casaco e Camisa de Poliamida Biodegradável",
        img: "img/roupas/masc7.jpg",
    },
    {
        id: "Oito",
        name: "Camisa Manga Longa Verde",
        price: 199,
        desc: "Verde Musgo 100% Algodão",
        img: "img/roupas/masc8.jpg",
    },
    {
        id: "Nove",
        name: "Jaqueta Cinza Masc",
        price: 175,
        desc: "Jaqueta mista de Algodão e Poliamida",
        img: "img/roupas/masc9.jpg",
    },
    {
        id: "Dez",
        name: "Casaco Casual Pastel",
        price: 153,
        desc: "O casco tom pastel é um tecido encorporado com superfície atoalhado",
        img: "img/roupas/masc10.jpg",
    },
    {
        id: "Um",
        name: "Roupão Branco",
        price: 45,
        desc: "100% Algodão",
        img: "img/roupas/masc11.jpg",
    },
    {
        id: "Dois",
        name: "Camiseta Colors",
        price: 100,
        desc: "Estampa Colorida 100% Linho",
        img: "img/roupas/masc12.jpg",
    },
];