let shopItemsData = [
    {
        id: "vuhhfsgfssf",
        name: "camisa social azul",
        price: 45,
        desc: "ser chic é se sustentavel",
        img: "img/roupas/fem1.jpg",
    },
    {
        id: "mnkjhbhf",
        name: "camisa social preta",
        price: 100,
        desc: "nossa roupa tras uma paz",
        img: "img/roupas/fem2.png",
    },
    {
        id: "nbvhvgcdfx",
        name: "camisa social branca",
        price: 25,
        desc: "seja sustentavel, seja chic!",
        img: "img/roupas/fem3.png",
    },
    {
        id: "gfdsrxkjnhb",
        name: "camisa social rosa",
        price: 200,
        desc: "seja sustentavel ",
        img: "img/roupas/fem4.jpg",
    },
    {
        id: "abc",
        name: "calça verde clara",
        price: 249,
        desc: "seja Northfield",
        img: "img/roupas/fem6.jpg",
    },
    {
        id: "def",
        name: "calça verde escuro",
        price: 70,
        desc: "seja perfeita",
        img: "img/roupas/fem7.jpg",
    },
    {
        id: "ghi",
        name: "calça rosa",
        price: 80,
        desc: "seja linda ",
        img: "img/roupas/fem10.jpg",
    },
    {
        id: "ggfhgjhg",
        name:"comjunto",
        price: 50,
        desc: "seja incrivel",
        img: "img/roupas/fem11.jpg",
    },
    
    {
        id: "lnkjhjjhbb",
        name: "calça escura",
        price: 45,
        desc: "seja a melhor ",
        img: "img/roupas/fem12.jpg",
    },
    {
        id: "kjhbkjbh",
        name: "calça rosa",
        price: 100,
        desc: "seja voce mesma ",
        img: "img/roupas/fem.13.jpg",
    },
    {
        id: "kjhbkj",
        name: "vestido curto",
        price: 200,
        desc: " voce é northfield",
        img: "img/roupas/fem14.jpg",
    },
    {
        id: "kjhuifgytd",
        name: "vestido curto",
        price: 250,
        desc: "voce é a melhor",
        img: "img/roupas/fem15.jpg",
    },
    {
        id: "Um",
        name: "camisetabranca",
        price: 45,
        desc: "Camiseta branca para criança",
        img: "img/roupas/masc1.jpg",
    },
    {
        id: "Dois",
        name: "Camiseta Linho",
        price: 100,
        desc: "Calça Leve 100% Linho",
        img: "img/roupas/masc2.jpg",
    },
    {
        id: "Três",
        name: "Roupão 100% algodão",
        price: 420,
        desc: "roupão para banho",
        img: "img/roupas/cammasc1.jpg",
    },
    {
        id: "Quatro",
        name: "Camisola masculina de algodão",
        price: 152,
        desc: "Lorem ipsum.",
        img: "img/roupas/masc4.jpg",
    },
    {
        id: "Cinco",
        name: "Casaco Masculino Algodão",
        price: 69,
        desc: "Casaco Masculino de Algodão ",
        img: "img/roupas/masc5.jpg",
    },
    {
        id: "Seis",
        name: "Camsisa xadrez em algodão",
        price: 200,
        desc: "Camisa importada masculina",
        img: "img/roupas/masc6.jpg",
    },
    {
        id: "Sete",
        name: "Camisa Masculina Manga longa Puro Linho",
        price: 598,
        desc: "A camisa verde é confeccionado em linho",
        img: "img/roupas/masc7.jpg",
    },
    {
        id: "Oito",
        name: "Jaqueta Masculina Stone Azul",
        price: 479,
        desc: "A jaqueta Azul é confeccionada em sarja leve",
        img: "img/roupas/masc8.jpg",
    },
    {
        id: "Nove",
        name: "Camisa Lilás Magnetada Manga Longa",
        price: 150,
        desc: "Jaqueta Pliamida",
        img: "img/roupas/masc9.jpg",
    },
    {
        id: "Dez",
        name: "Casaco Masculino",
        price: 453,
        desc: "O casco marrom",
        img: "img/roupas/masc10.jpg",
    },
    {
        id: "Um",
        name: "Roupão",
        price: 45,
        desc: "Camiseta branca",
        img: "img/roupas/masc11.jpg",
    },
    {
        id: "Dois",
        name: "Camiseta",
        price: 100,
        desc: "Calça Leve 100% Linho",
        img: "img/roupas/masc12.jpg",
    },
];